// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA12DRUnFM43irVXdssAdh5P_9WXtdWUks',
    appId: '1:806584624803:web:6bfd9c3b0b77b0c80d4116',
    messagingSenderId: '806584624803',
    projectId: 'tfg-dam-lucia-angela',
    authDomain: 'tfg-dam-lucia-angela.firebaseapp.com',
    storageBucket: 'tfg-dam-lucia-angela.firebasestorage.app',
    measurementId: 'G-2D47HC3H5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3qLusvX6GK_uyfOPwwtKQmisd3qbmpuw',
    appId: '1:806584624803:android:0aac1d6eaaaa43420d4116',
    messagingSenderId: '806584624803',
    projectId: 'tfg-dam-lucia-angela',
    storageBucket: 'tfg-dam-lucia-angela.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOR1JEVjDU4Uzb0oUqyQd8WTpCJW-n2aw',
    appId: '1:806584624803:ios:6aea096a8cbc975e0d4116',
    messagingSenderId: '806584624803',
    projectId: 'tfg-dam-lucia-angela',
    storageBucket: 'tfg-dam-lucia-angela.firebasestorage.app',
    androidClientId: '806584624803-19ipsne1t8ff5clpvv68cbdsanqhjdom.apps.googleusercontent.com',
    iosClientId: '806584624803-qpvbcnohdtusednugvvtdm4q4gdgfkl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfgBettervibes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA12DRUnFM43irVXdssAdh5P_9WXtdWUks',
    appId: '1:806584624803:web:eb422a015c9777c80d4116',
    messagingSenderId: '806584624803',
    projectId: 'tfg-dam-lucia-angela',
    authDomain: 'tfg-dam-lucia-angela.firebaseapp.com',
    storageBucket: 'tfg-dam-lucia-angela.firebasestorage.app',
    measurementId: 'G-4CD463DPLT',
  );
}
